// Clerk theming mapped to the Organoli design tokens.
export const clerkAppearance = {
  cssLayerName: "clerk",
  variables: {
    colorPrimary: "#4A656D",
    colorPrimaryForeground: "#F2F1ED",
    colorBackground: "#F2F1ED",
    colorForeground: "#24343A",
    colorMutedForeground: "#4E6870",
    colorMuted: "#E4E2DC",
    colorInput: "#FAF9F6",
    colorInputForeground: "#24343A",
    colorBorder: "#CFCCC4",
    colorRing: "#7FB9A1",
    colorNeutral: "#24343A",
    colorDanger: "#A3473A",
    colorSuccess: "#4E856E",
    fontFamily: "var(--font-barlow), Barlow, system-ui, sans-serif",
    fontFamilyButtons: "var(--font-barlow), Barlow, system-ui, sans-serif",
    fontSize: "15px",
    borderRadius: "2px",
  },
  elements: {
    rootBox: "w-full",
    cardBox: "w-full max-w-[460px] shadow-none rounded-sm border border-hairline",
    card: "shadow-none bg-paper px-8 py-9",
    headerTitle: "font-display text-[34px] font-medium leading-none tracking-normal text-ink",
    headerSubtitle: "text-[15px] text-slate-text",
    formFieldLabel: "text-[11px] font-semibold uppercase tracking-[.14em] text-slate-text",
    socialButtonsBlockButton: "h-12 rounded-sm border-hairline bg-field shadow-none",
    dividerLine: "bg-hairline",
    formFieldInput: "h-12 rounded-sm border-hairline bg-field text-base focus:border-ink",
    formButtonPrimary: "h-14 rounded-sm bg-slate-700 text-[13px] font-semibold uppercase tracking-[.16em] shadow-none hover:bg-ink",
    footer: "bg-paper-shade",
    footerActionLink: "font-semibold text-ink underline underline-offset-[3px]",
    userButtonAvatarBox: "h-8 w-8",
    userButtonPopoverCard: "rounded-sm border border-hairline shadow-mega",
  },
} as const;

/** For forms set inside the AuthShell label: Clerk's own card, header and switch link are removed. */
export const labelAppearance = {
  ...clerkAppearance,
  elements: {
    ...clerkAppearance.elements,
    rootBox: "!w-full",
    cardBox: "!w-full !max-w-none !shadow-none !border-0 !rounded-none !bg-transparent",
    card: "!w-full !shadow-none !border-0 !rounded-none !bg-transparent !p-0 !gap-6",
    header: "hidden",
    main: "!w-full",
    form: "!w-full",
    footer: "!bg-transparent !bg-none mt-2 !p-0 [&>div]:!bg-transparent [&>div]:!px-0",
    footerAction: "hidden",
    formFieldInput: "h-12 rounded-sm border-hairline bg-field text-base shadow-none focus:border-ink",
    formButtonPrimary: "h-14 rounded-sm bg-slate-700 text-[13px] font-semibold uppercase tracking-[.16em] shadow-none hover:bg-ink",
  },
} as const;
